### ISSUE TITLE
Use Google Benchmark for C++

### ISSUE THREAD

**Issue by Roger-luo** [astrojhgu/adaptrapezoid_benchmark#1]
你好，在知乎上看到你的文章，文章里面使用terminal的time测试时间是不准确的，这个时间会随着实际物理情况发生改变。请使用各个语言里较为受欢迎的性能测试框架进行测试。

C++:

https://github.com/google/benchmark

Python: `timeit`

Julia: `BenchmarkTools`

rust:

https://doc.rust-lang.org/1.1.0/test/struct.Bencher.html

其它的语言我不太熟悉，但是原理上应当对一个任务进行多次运行，然后取平均值。最后你的benchmark数据应当有mean value，min value，max value，mid value组成。

**Comment by astrojhgu** [comment]
Roger and done.
