### ISSUE TITLE
unnecessary type annotation etc.

### ISSUE THREAD

**Issue by Roger-luo** [astrojhgu/adaptrapezoid_benchmark#2]
https://github.com/astrojhgu/adaptrapezoid_benchmark/blob/67579e58f640920168b44837ef02e7e61d06c7b9/jl/main.jl#L9

你对Julia的速度有误解。Julia是一个会进行编译的动态语言，而非依靠对静态编译进行妥协而获得性能提升。代码里面很多类型标注都并非是必要的，它们完全可以在你输入变量以后通过类型推导确定下来。如果你想理解为什么Julia快可以阅读 [为什么Julia这么快](https://juejin.im/post/5b75911af265da27fc07a256) ，也可以尝试阅读arxiv上的论文原文。

Julia的所有类型都是动态类型，和Python最大的区别在于不能动态修改代码，只允许动态生成代码。但这一点我们实际上只有在非常少的情况下才会在数值计算任务里用到。

速度快慢的重点在于保证类型的稳定性，还请仔细阅读文档，你可以使用`@code_warntype`快速检查你的类型稳定性。这是因为Julia采用了box type模型。这会要求你在使用AbstractFloat这样的抽象类型时尽可能把代码写的抽象和一般性，当然这也是使用AbstractFloat的原因所在。

关于Julia的美感问题，你没有严格按照style guide编写程序。Julia的函数是会对类型进行pattern match的，也就是多重派发，利用好这一点，程序可以写的很漂亮。推荐你阅读：

https://github.com/jrevels/YASGuide

以及一些常见的design pattern:

https://docs.julialang.org/en/v1/manual/methods/#Design-Patterns-with-Parametric-Methods-1

数值积分实际上已经有很多纯Julia实现了，在闭门造轮子前不妨先看看其它开发者的代码：

https://github.com/JuliaMath/QuadGK.jl

好的Julia程序速度应当接近C++，而不是仅仅满足于比Python快。开发完毕以后可以封装到module里，然后进行预编译，或者AOT编译去掉JIT overhead。

祝好

**Comment by Roger-luo** [comment]
然后附上一个benchmark供你参考，你的实现大概比QuadGK的这个纯Julia实现慢了98421倍：

```
julia> @benchmark quadgk(x->sin(x^2), 0.0, 1.0, 2.0, sqrt(8*pi), rtol=1e-10)
BenchmarkTools.Trial:
  memory estimate:  4.09 KiB
  allocs estimate:  199
  --------------
  minimum time:     6.952 μs (0.00% GC)
  median time:      7.654 μs (0.00% GC)
  mean time:        9.387 μs (12.94% GC)
  maximum time:     7.947 ms (99.85% GC)
  --------------
  samples:          10000
  evals/sample:     5

julia> @benchmark integrate(x->sin(x^2), [0.0, 1.0, 2.0, sqrt(8*pi)], 1e-10)
BenchmarkTools.Trial:
  memory estimate:  90.57 MiB
  allocs estimate:  4450430
  --------------
  minimum time:     637.591 ms (0.00% GC)
  median time:      748.192 ms (13.52% GC)
  mean time:        746.844 ms (14.42% GC)
  maximum time:     831.827 ms (23.68% GC)
  --------------
  samples:          7
  evals/sample:     1
```

**Comment by astrojhgu** [comment]
谢谢，我注意到我对Julia的类型标记理解有误。我更新了程序，把函数写成了泛型风格+类型约束。另一方面，我也测试过完全不加类型标记，结果发现速度将显著下降。

我目前提交的版本（b4a3846）的速度大致是C++版本的一半。算是一个比较满意的速度了。

另外你提到的这个QuadGK 的这个积分方法，它属于高斯积分法，并不能直接拿来和我这里使用的自适应梯形积分法做比较

**Comment by Roger-luo** [comment]
你的benchmark代码是错误的，应当测量 `integrate`函数本身的时间而不是 算上 `println`的时间。速度下降是因为你写出来类型不稳定的代码，而不是因为没有标注静态类型。请你仔细阅读performance tips以及使用code_warntype检查。

给你看QuadGK不是让你看积分方法，而是看别人的实现，看看专业做数值的人是怎么写代码的。凭自己想象写出来的代码肯定是很奇怪也很丑的。
